[package]
name = "root"
version = "0.1.0"
edition = "2021"

[dependencies]
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }
chrono = "0.4"

[[bin]]
name = "app"
path = "cmd/app/main.rs"
